# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "ipython==9.17.0",
#     "marimo>=0.23.16",
#     "pandas==3.0.5",
#     "py2opsin==1.2.0",
#     "rdkit==2025.9.3",
# ]
# ///

import marimo

__generated_with = "0.24.0"
app = marimo.App(width="full", auto_download=["html"])


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    **Background**

    The following code are just my random coding sessions trying to see if some of the common cheminformatics Python packages can be used in a Marimo notebook. I'm also trying to become more familiar with functional groups in SMILES (Simplified Molecular Input Line Entry System) too... and realise I may enter into a very complex area just by wanting to do this. At this stage, I'm going to make this little piece of work as an entry point to the world of molecular representations, with a main focus on SMILES only for now.

    *This is going to be worked on in a random and spontaneous mode... so it may not be very coherent at first.*

    <br>

    **Plan for exporting/publishing this little notebook in the end**

    - Had a quick look at marimo glance (https://github.com/marimo-team/marimo-glance), it turns out that it's an option to view marimo notebook at a glance as it's a web browser extension that can be installed to view marimo notebook from GitHub, gist or GitLab in a Chrome or Firefox browser. One limitation is the notebook needs to be compatible with WebAssembly for this extension to work.

    - Other options to export or publish marimo notebooks - https://docs.marimo.io/guides/exporting/ and https://docs.marimo.io/guides/publishing/

    - So likely this piece will be published on the Quarto blog instead
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    **Starting a Marimo notebook**

    To create or edit a marimo notebook, use the command: *marimo edit notebook_filename.py* in the terminal ([link](https://docs.marimo.io/getting_started/quickstart/) to show other related commands). It will then ask if you'd like to run this notebook in a sandboxed venv containing this notebooks's dependencies. By answering yes, this'll immediately take you to the notebook opened in your default web browser. This requires marimo to be installed earlier, and this Marimo [link](https://docs.marimo.io/getting_started/installation/) shows how to do it.

    **Other features of Marimo notebooks**

    - Work well with uv, a Python package installer and manager

    - Currently only work with Python programming language and not other languages (unless new plans are announced by the Marimo team)

    - Exist as a Python script so if it is opened in an editor (e.g. VS Code), it'll look different (Figure 1) from how it appears in a browser as the code inside the notebook will look like it's for an application (implying that you can make interactive apps by using Marimo...!)

    **Conversion between different notebook or file formats**

    This [link](https://docs.marimo.io/guides/coming_from/jupyter/) shows how to convert a Jupyter notebook into a Marimo notebook, export a Marimo notebook into a Jupyter notebook or convert a Python script into a Marimo notebook, and other relevant information.
    """)
    return


@app.cell
def _():
    # apparently need this line below so markdown cells can be used
    import marimo as mo

    return (mo,)


@app.cell
def _(mo):
    # insert image doc link - https://docs.marimo.io/api/media/image/
    mo.image(src="marimo_py.jpg", width=850, height=450, caption="Fig.1 - A partial screenshot of a Marimo notebook Python script in VS Code")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    **About Simplified Molecular Input Line Entry System (SMILES)**

    There are different types of canonical SMILES available as they can be generated by different algorithms made by different software development groups (e.g. [Daylight Chemical Information Systems](https://www.daylight.com/dayhtml/doc/theory/index.html), and a few others to be named).

    Some useful references for beginners to learn about what SMILES strings are:
    - https://en.wikipedia.org/wiki/Simplified_Molecular_Input_Line_Entry_System (for general overview)
    - https://archive.epa.gov/med/med_archive_03/web/html/smiles.html
    - https://www.epa.gov/sites/default/files/2015-05/documents/appendf.pdf
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Importing and trying out RDKit first.
    """)
    return


@app.cell
def _():
    # sample code only
    from rdkit import Chem
    from rdkit.Chem.Draw import IPythonConsole
    from rdkit.Chem import Draw
    #IPythonConsole.ipython_useSVG=True
    return (Chem,)


@app.cell
def _(Chem):
    mol_1 = Chem.MolFromSmiles('COC(=O)CNC(=O)CCCO')
    mol_1
    return (mol_1,)


@app.cell
def _(Chem):
    mol_2 = Chem.MolFromSmiles("C1=CC=CC=C1")
    mol_2
    return


@app.cell
def _(Chem, mol_1):
    # Finding out the presence of substructures (or potentially functional groups) in a particular molecule
    f_group = Chem.MolFromSmarts('C=O')
    matches = mol_1.GetSubstructMatches(f_group)
    len(matches)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    The following is a small side track to see if py2opsin will work, which is based on [opsin](https://www.ebi.ac.uk/opsin/).
    """)
    return


@app.cell
def _():
    # https://github.com/dan2097/opsin
    # https://github.com/JacksonBurns/py2opsin
    from py2opsin import py2opsin
    import pandas as pd

    return pd, py2opsin


@app.cell
def _(py2opsin):
    smiles_string = py2opsin(
        chemical_name = ["ethane", "cyclopentane", "benzene", "pyridine"], 
        output_format = "SMILES",
    )

    smiles_string
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Will likely try to draw the following drugs in 2D and see if I can do something about their function groups (i.e. show function groups from each drug?)
    """)
    return


@app.cell
def _(pd):
    # if using pd.read_csv, all 5 columns are grouped into one column (unsure why, perhaps it's only reading .csv files well and not .tsv ones?), pd.read_table solves this
    df = pd.read_table("cyp3a4_smiles.tsv")
    df.head()
    return (df,)


@app.cell
def _(df):
    smiles_ls = list(df["canonical_smiles"])
    smiles_ls
    return (smiles_ls,)


@app.cell
def _(smiles_ls):
    type(smiles_ls)
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
